import { useEffect, useState, type ReactNode } from "react";
import "./App.css";
import { Markdown, parseDocument, type MarkdownDocument } from "./markdown";
import { siteConfig } from "./siteConfig";

const BASE_PATH = import.meta.env.BASE_URL.endsWith("/") ? import.meta.env.BASE_URL.slice(0, -1) : import.meta.env.BASE_URL;
function toSiteUrl(path: string) { if (!path.startsWith("/")) return path; return `${BASE_PATH}${path || "/"}` || "/"; }
function currentSitePath() { const pathname=window.location.pathname; if(BASE_PATH&&pathname.startsWith(BASE_PATH)){const stripped=pathname.slice(BASE_PATH.length);return stripped||"/";} return pathname||"/"; }
function navigate(path:string){window.history.pushState({},"",toSiteUrl(path));window.dispatchEvent(new PopStateEvent("popstate"));window.scrollTo({top:0,behavior:"smooth"});}
function SiteLink({href,children,className}:{href:string;children:ReactNode;className?:string}){const external=/^(https?:)?\/\//.test(href);return <a href={external?href:toSiteUrl(href)} className={className} onClick={(e)=>{if(!external&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();navigate(href);}}}>{children}</a>;}
function Header(){return <header className="site-header"><SiteLink className="brand" href="/"><span className="brand-mark">{siteConfig.shortMark}</span><span><strong>{siteConfig.name}</strong><small>{siteConfig.subtitle}</small></span></SiteLink><nav className="nav" aria-label="Primary navigation">{siteConfig.navigation.map(i=><SiteLink href={i.href} key={i.href}>{i.label}</SiteLink>)}</nav></header>;}
function Home({document}:{document:MarkdownDocument}){const{meta,body}=document;return <><section className="hero"><div className="hero-copy"><p className="kicker">{meta.kicker||"ROSEFIRE ROLEPLAY"}</p><h1>{meta.title||"ROSEFIRE RP"}</h1><p className="hero-motto">{meta.motto||"PLAYABLE AT 1. ALIVE AT 50."}</p><p className="lede">{meta.description}</p><div className="hero-actions"><SiteLink className="button primary" href="/getting-started">Enter Rosefire</SiteLink><SiteLink className="button secondary" href="/rules">Read the rules</SiteLink></div></div><aside className="state-card"><p className="status-label">CURRENT STATUS</p><p className="status-value"><span/> {meta.status||"FOUNDING TESTERS"}</p><p>{meta.statusText||"Rosefire is in active development and preparing for its first outside testers."}</p></aside></section><article className="markdown-content home-content"><Markdown source={body}/></article></>;}
function DocumentPage({document}:{document:MarkdownDocument}){return <article className="page-shell markdown-content">{document.meta.eyebrow&&<p className="section-kicker">{document.meta.eyebrow}</p>}<Markdown source={document.body}/>{document.meta.updated&&<p className="updated">Last updated: {document.meta.updated}</p>}</article>;}
function App(){const[path,setPath]=useState(currentSitePath());const[document,setDocument]=useState<MarkdownDocument|null>(null);const[missing,setMissing]=useState(false);useEffect(()=>{const h=()=>setPath(currentSitePath());window.addEventListener("popstate",h);return()=>window.removeEventListener("popstate",h);},[]);useEffect(()=>{const file=siteConfig.pages[path];setDocument(null);setMissing(!file);if(!file)return;fetch(`${import.meta.env.BASE_URL}content/${file}`).then(r=>{if(!r.ok)throw new Error("Unable to load page");return r.text();}).then(s=>{setDocument(parseDocument(s));setMissing(false);}).catch(()=>{setDocument(null);setMissing(true);});},[path]);return <main><Header/>{missing?<section className="page-shell"><p className="section-kicker">404</p><h1>That road is closed.</h1><p className="page-intro">The page you were looking for does not exist.</p><SiteLink className="button primary" href="/">Return home</SiteLink></section>:!document?<section className="page-shell"><p className="page-intro">Loading Rosefire…</p></section>:path==="/"?<Home document={document}/>:<DocumentPage document={document}/>}<footer><div><strong>ROSEFIRE RP</strong><p>Playable at 1. Alive at 50.</p></div><SiteLink href="/rules">Rules</SiteLink></footer></main>;}
export default App;
